# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Platform Universe Map
description: > # this means to ignore newlines until "baseurl:"
  Web platform - collection of technologies powering modern web. Purpose of this project is to map all existing standards and initiatives
baseurl: '/web-platform-universe-map'
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: stereobooster
github_username:  stereobooster

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

exclude:
  - 'node_modules'
  - 'bin'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'

gems:
  - jekyll-seo-tag
